version: '3.7'

services:
  studocu-cli-test:
    container_name: studocu-cli-test
    image: studocu:cli
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: tail -f /dev/null
    volumes:
      - .:/studocu
    environment:
      APP_ENV: testing
    depends_on:
      - studocu-database-test

  studocu-database-test:
    container_name: studocu-database-test
    image: postgres
    restart: always
    ports:
      - 5544:5432
    environment:
      POSTGRES_DB: studocu-test
      POSTGRES_USER: studocu-test
      POSTGRES_PASSWORD: 123456
